#!/usr/bin/env bash
# Install nginx web server
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Holberton School is Fun!' >/var/www/html/index.nginx-debian.html
service nginx start
