#!/usr/bin/env bash
# /redirect_me is redirecting to another page
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Holberton School for the win!' >/var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.holbertonschool.com/co permanent;' /etc/nginx/sites-available/default
nginx -s reload
