#!/usr/bin/env bash
# Install nginx web server and config custom header
apt-get -y remove nginx nginx-common
apt-get -y autoremove
apt-get -y purge nginx nginx-common
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Holberton School for the win!' >/var/www/html/index.nginx-debian.html
sed -i "/location/a add_header X-Served-By $hostname;" /etc/nginx/sites-available/default
service nginx reload
