#!/usr/bin/env bash
# Install nginx web server and config custom header
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo sed -i "26i add_header X-Served-By \$hostname;" /etc/nginx/sites-available/default
service nginx restart
