#!/usr/bin/env bash
# Install and configure HAproxy
apt-get install software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-1.8 -y
apt-get update -y
apt-get install haproxy=1.8.\* -y
echo "
    frontend http-in
        bind *:80
        mode http
        default_backend servers

    backend servers
        balance roundrobin
        server 907-web-01 35.229.36.131:80 check
        server 907-web-02 34.74.68.170:80  check
" >>/etc/haproxy/haproxy.cfg
service haproxy restart
