#!/usr/bin/env bash
# Install and configure HAproxy
apt-get install software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0 -y
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo "
    frontend http-in
        bind *:80
        mode http
        default_backend servers

    backend servers
        balance roundrobin
        server 907-web-01 35.229.36.131:80 check
        server 907-web-02 34.74.68.170:80  check
" >>/etc/haproxy/haproxy.cfg
service haproxy restart
