#!/usr/bin/env bash
# Install and configure HAproxy
apt-get install software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0 -y
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo "
    frontend http-in
        bind *:80
        default_backend servers

    backend servers
        server server1 35.229.36.131 maxconn 32
        server server2 34.74.68.170  maxconn 32
" >>/etc/haproxy/haproxy.cfg
service haproxy restart
