#!/usr/bin/env bash
# This script displays Holberton School and then Hi on a new line
x=1
while (("$x" <= 10)); do
	echo "Holberton School"
	if [ "$x" -eq 9 ]; then
		echo "Hi"
	fi
	x=$((x + 1)) # increment $x
done
