#!/usr/bin/env bash
# This script displays Holberton School and then Hi on a new line
x=1
while (("$x" <= 10)); do
	if [ "$x" -eq 9 ]; then
		echo "Hi"
	else
		echo "Holberton School"
	fi

	x=$((x + 1)) # increment $x
done
