#!/usr/bin/env bash
# This script displays Holberton School and then Hi on a new line
	FILE = "$(pwd)/holbertonschool"
	if [[ -e  $FILE ]]; then
	echo "holbertonschool file exists"
	if [[ $FILE ]]; then
		echo
	fi
	else
	echo "holbertonschool file does not exist"
	fi
